name: Android CI

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: clone repo and submodules
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}
        submodules: true
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Add secret API Key
      run: echo "MAPS_API_KEY=\""${{ secrets.MAPS_API_KEY }}"\"" >> local.properties
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          id: app_id
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

    - name: Download APK
      uses: actions/download-artifact@v1
      id: download
      with:
          name: app
          path: /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android/src/main/resources

    - name: list app folder
      run: |
        ls -la /home/runner/work/onbeatcicd/onbeatcicd/app
        ls -la /home/runner/work/onbeatcicd/onbeatcicd/app/build/outputs/apk/debug
        chmod +x /home/runner/work/onbeatcicd/onbeatcicd/app/build/outputs/apk/debug/app-debug.apk
        chmod +x /home/runner/work/onbeatcicd/onbeatcicd/app/build/outputs/apk/debug/app-debug.apk
        ls -la /home/runner/work/onbeatcicd/onbeatcicd/app
        ls -la /home/runner/work/onbeatcicd/onbeatcicd/app/build/outputs/apk/debug

#    - name: list app folder
#      run: |
#        ls -la /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android
#        ls -la /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android/src/main/resources
#        chmod +x /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android/src/main/resources/app-debug.apk
#        chmod +x /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android/src/main/resources/app-debug.apk
#        ls -la /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android
#        ls -la /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android/src/main/resources

    - name: Open and list sub-dir
      run: |
        chmod +x ./onbeat-qa-automation-android/src/test/java/com/qa/runners/MyRunnerTest.java
        ls -la ./onbeat-qa-automation-android/src/test/java/com/qa/runners
    
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: |
            npm install -g appium@v1.20.2
            appium -v
            appium &>/dev/null &


#    - name: list app folder before QA script
#      run: |
#          ls -la /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android
#          ls -la /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android/src/main/resources
#          chmod +x /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android/src/main/resources/app-debug.apk
#          chmod +x /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android/src/main/resources/app-debug.apk
#          ls -la /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android
#          ls -la /home/runner/work/onbeatcicd/onbeatcicd/onbeat-qa-automation-android/src/main/resources

    - name: list app folder before QA script
      run: |
        ls -la /home/runner/work/onbeatcicd/onbeatcicd/app
        ls -la ../../../../../../home/runner/work/onbeatcicd/onbeatcicd/app/build
        ls -la /home/runner/work/onbeatcicd/onbeatcicd/app/build/outputs/apk/debug
        chmod +x /home/runner/work/onbeatcicd/onbeatcicd/app/build/outputs/apk/debug/app-debug.apk
        chmod +x /home/runner/work/onbeatcicd/onbeatcicd/app/build/outputs/apk/debug/app-debug.apk
        ls -la /home/runner/work/onbeatcicd/onbeatcicd/app
        ls -la /home/runner/work/onbeatcicd/onbeatcicd/app/build/outputs/apk/debug


    - name: QA Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
       api-level: 29
       target: default
       arch: x86_64
       working-directory: ./onbeat-qa-automation-android
       script: |
        pwd
        ls -l
        mvn clean test
       
            
